/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#00174b",
        "tertiary": "#ffb95f",
        "on-secondary-fixed": "#002113",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-container": "#00a572",
        "on-tertiary-container": "#ffeedd",
        "surface-container-lowest": "#0c0e16",
        "surface-container": "#1d1f27",
        "surface-bright": "#373942",
        "outline": "#8d90a0",
        "on-tertiary-fixed-variant": "#653e00",
        "outline-variant": "#434655",
        "on-secondary-container": "#00311f",
        "surface": "#11131b",
        "secondary-fixed-dim": "#4edea3",
        "on-surface": "#e1e2ed",
        "on-error": "#690005",
        "on-surface-variant": "#c3c6d7",
        "on-secondary": "#003824",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e1e2ed",
        "surface-variant": "#32343d",
        "surface-container-high": "#282a32",
        "background": "#11131b",
        "on-background": "#e1e2ed",
        "inverse-primary": "#0053db",
        "secondary-fixed": "#6ffbbe",
        "surface-dim": "#11131b",
        "on-secondary-fixed-variant": "#005236",
        "on-tertiary-fixed": "#2a1700",
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-low": "#191b23",
        "primary": "#b4c5ff",
        "on-tertiary": "#472a00",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-fixed": "#ffddb8",
        "primary-container": "#2563eb",
        "error-container": "#93000a",
        "on-primary": "#002a78",
        "surface-tint": "#b4c5ff",
        "surface-container-highest": "#32343d",
        "tertiary-container": "#996100",
        "inverse-on-surface": "#2e3039",
        "secondary": "#4edea3",
        "on-primary-container": "#eeefff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "gutter": "16px",
        "lg": "24px",
        "xs": "8px",
        "margin-mobile": "16px",
        "sm": "12px",
        "xl": "32px",
        "base": "4px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "500" }],
        "label-bold": ["14px", { "lineHeight": "20px", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "900" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "800" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "800" }]
      }
    },
  },
  plugins: [],
}
